sonar.projectKey=JesusJC15_salud-de-una-web
sonar.organization=jesusjc15
sonar.sourceEncoding=UTF-8

sonar.sources=src
sonar.tests=src
sonar.test.inclusions=src/**/*.test.ts,src/**/*.test.tsx,src/**/*.spec.ts,src/**/*.spec.tsx,src/**/__tests__/**,src/**/__test__/**,src/**/*.e2e-spec.ts
sonar.exclusions=**/node_modules/**,**/.next/**,**/dist/**,**/coverage/**
sonar.coverage.exclusions=src/components/**,src/app/**,src/features/**/components/**,src/features/**/pages/**,src/features/**/layouts/**,src/features/**/hooks/**,src/features/**/constants/**
sonar.typescript.tsconfigPaths=tsconfig.json,tsconfig.jest.json

sonar.javascript.lcov.reportPaths=coverage/lcov.info
