export enum ProgramType {
  DOCTORATE = "DOCTORATE",
  UNDEFINED = "UNDEFINED",
  PROFESSIONAL_TECHNICAL = "PROFESSIONAL_TECHNICAL",
  MASTERS = "MASTERS",
  TECHNOLOGY = "TECHNOLOGY",
  SPECIALIZATION = "SPECIALIZATION",
  UNIVERSITY = "UNIVERSITY",
  ASSISTANT = "ASSISTANT",
}